#include <map>
#include <string>

using namespace std;

map<int, string> vertices {
    {1, "Armenia"},
    {2, "Albania"},
    {3, "Andorra"},
    {4, "Austria"},
    {5, "Belarus"},
    {6, "Belgium"},
    {7, "Bosnia and Herzegovina"},
    {8, "Bulgaria"},
    {9, "Croatia"},
    {10, "Cyprus"},
    {11, "Czech Republic"},
    {12, "Denmark"},
    {13, "Estonia"},
    {14, "Finland"},
    {15, "France"},
    {16, "Germany"},
    {17, "Georgia"},
    {18, "Greece"},
    {19, "Hungary"},
    {20, "Iceland"},
    {21, "Ireland"},
    {22, "Italy"},
    {23, "Kosovo"},
    {24, "Latvia"},
    {25, "Liechtenstein"},
    {26, "Lithuania"},
    {27, "Luxembourg"},
    {28, "Malta"},
    {29, "Moldova"},
    {30, "Monaco"},
    {31, "Montenegro"},
    {32, "Netherlands"},
    {33, "North Macedonia"},
    {34, "Norway"},
    {35, "Poland"},
    {36, "Portugal"},
    {37, "Romania"},
    {38, "Russia"},
    {39, "San Marino"},
    {40, "Serbia"},
    {41, "Slovakia"},
    {42, "Slovenia"},
    {43, "Spain"},
    {44, "Sweden"},
    {45, "Switzerland"},
    {46, "Turkey"},
    {47, "Ukraine"},
    {48, "United Kingdom"},
    {49, "Vatican City"},
};